name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: docker build -t flaskapp .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_0123.0123 }}" | docker login -u "${{ secrets.DOCKER_sirine3443 }}" --password-stdin

    - name: Push Docker image
      run: docker tag flaskapp:latest sirine3443/flaskapp:latest && docker push sirine3443/flaskapp:latest
